# NumPy Arrays

In [140]:
my_list = [1,2,3]

In [141]:
import numpy as np
np.array(my_list)

array([1, 2, 3])

In [142]:
type(np.array(my_list))

numpy.ndarray

In [143]:
arr1 = np.array(my_list)
print(f"arr1 : {arr1} arr1 | Type : {type(arr1)}")

arr1 : [1 2 3] arr1 | Type : <class 'numpy.ndarray'>


# A 2D array 

In [144]:
mat1 = [[1,2,3,],[4,5,6,],[7,8,9]]
print(f"Type mat1 : {type(mat1)}")

Type mat1 : <class 'list'>


In [145]:
#conversion to 2D array with 3 rows and 3 columns

In [146]:
print(f"{np.array(mat1)}")

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [147]:
print(f"Type : {type(np.array(mat1))}")

Type : <class 'numpy.ndarray'>


# arange() Method

In [148]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [149]:
type(np.arange(0,10))

numpy.ndarray

In [150]:
arr2 = np.arange(0,11,2)

In [151]:
arr2

array([ 0,  2,  4,  6,  8, 10])

In [152]:
for i in range(0,len(arr2)):
    print(arr2[i])

0
2
4
6
8
10


In [153]:
np.zeros(3)

array([0., 0., 0.])

In [154]:
np.ones(3)

array([1., 1., 1.])

In [155]:
# Each element in generator function is a float data type

In [156]:
print(type(np.zeros(3)[0]))

<class 'numpy.float64'>


# np.zeros(rows,columns)
# np.ones(rows,columns)

In [157]:
# the ones and zeros array

zero_arr = np.zeros((10,10))
one_arr = np.ones((10,10))

print(f"{zero_arr}")
print(f"{one_arr}")

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


# np.linspace(start,stop,numberOfElements)

In [158]:
import math
print(f"{np.linspace(0,math.pi,10)}")
# 10 evenly spaced number between 0 and PI

[0.         0.34906585 0.6981317  1.04719755 1.3962634  1.74532925
 2.0943951  2.44346095 2.7925268  3.14159265]


# Identity Matrix

In [159]:
id_mat = np.eye(4)
print(f"{id_mat}")

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Random Arrays

In [160]:
np.random.rand(5)

array([0.31187795, 0.64701823, 0.47748596, 0.30610374, 0.47294465])

In [161]:
np.random.rand(5,5)

array([[0.09531862, 0.52701096, 0.83781704, 0.12041837, 0.42091511],
       [0.82269656, 0.5801965 , 0.26145357, 0.47774172, 0.93311817],
       [0.6404047 , 0.2755877 , 0.30607047, 0.67526273, 0.78932648],
       [0.2222504 , 0.92915201, 0.3519094 , 0.69370165, 0.62839663],
       [0.79455747, 0.52050315, 0.13320325, 0.30965211, 0.6354036 ]])

In [162]:
np.random.randn(2,2)

array([[-0.8105461 ,  0.00947074],
       [-0.04669113, -0.27218424]])

In [163]:
np.random.randint(1,50)

6

In [164]:
np.random.randint(1,50,5)

array([45, 48, 48, 34,  1])

In [165]:
arr3 = np.arange(0,25,1)

In [166]:
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [167]:
arr3.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# Maximum , Minimum & Index Locations

In [168]:
rand_arr = np.random.randint(100,200,25)

In [169]:
rand_arr.reshape(5,5)

array([[186, 173, 177, 155, 108],
       [177, 125, 176, 153, 112],
       [173, 124, 157, 199, 180],
       [183, 100, 110, 145, 166],
       [103, 148, 138, 177, 194]])

In [170]:
print(f"Max Value : {rand_arr.max()} \nMin Value : {rand_arr.min()} \nRange : {rand_arr.max()-rand_arr.min()} \nIndex Position of Max Element : {rand_arr.argmax()} \nIndex Position of Min Element : {rand_arr.argmin()}")

Max Value : 199 
Min Value : 100 
Range : 99 
Index Position of Max Element : 13 
Index Position of Min Element : 16


In [171]:
rand_arr[19]

166

In [172]:
rand_arr[11]

124

In [173]:
arr4 = rand_arr.reshape(5,5)

In [174]:
arr4.shape

(5, 5)

In [175]:
arr4.dtype

dtype('int32')

In [176]:
type(arr4[0][1])

numpy.int32

In [177]:
from numpy import random
rand_arr1 = random.randint(0,100,20)
print(f"{rand_arr1}")

[74  3 81 96 73 15 85  3 52 73 72 63 25 99 60 57 42 70 64 77]


In [178]:
#alternative way

In [179]:
from numpy.random import randint
rand_arr2 = randint(0,100,20)
print(f"{rand_arr2}")

[24 23 68 76 75 18 27 28 23 29 63 73 93  9 36 84  4 55 37  6]


In [180]:
common_random_numbers_list = []
for i in rand_arr1:
    if i in rand_arr2:
        common_random_numbers_list.append(i)
print(f"Common Random  +ve Integers : {common_random_numbers_list}")

Common Random  +ve Integers : [73, 73, 63]


# Arrays Slicing . Indexing . Selection .

In [182]:
arr1 = np.arange(0,11)

In [183]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [184]:
arr1[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [185]:
arr1[1:5]

array([1, 2, 3, 4])

In [186]:
arr1[0]

0

In [187]:
type(arr1[0])

numpy.int32