# NumPy Arrays

In [186]:
my_list = [1,2,3]

In [187]:
import numpy as np
np.array(my_list)

array([1, 2, 3])

In [188]:
type(np.array(my_list))

numpy.ndarray

In [189]:
arr1 = np.array(my_list)
print(f"arr1 : {arr1} arr1 | Type : {type(arr1)}")

arr1 : [1 2 3] arr1 | Type : <class 'numpy.ndarray'>


# A 2D array 

In [190]:
mat1 = [[1,2,3,],[4,5,6,],[7,8,9]]
print(f"Type mat1 : {type(mat1)}")

Type mat1 : <class 'list'>


In [191]:
#conversion to 2D array with 3 rows and 3 columns

In [192]:
print(f"{np.array(mat1)}")

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [193]:
print(f"Type : {type(np.array(mat1))}")

Type : <class 'numpy.ndarray'>


# arange() Method

In [194]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [195]:
type(np.arange(0,10))

numpy.ndarray

In [196]:
arr2 = np.arange(0,11,2)

In [197]:
arr2

array([ 0,  2,  4,  6,  8, 10])

In [198]:
for i in range(0,len(arr2)):
    print(arr2[i])

0
2
4
6
8
10


In [199]:
np.zeros(3)

array([0., 0., 0.])

In [200]:
np.ones(3)

array([1., 1., 1.])

In [201]:
# Each element in generator function is a float data type

In [202]:
print(type(np.zeros(3)[0]))

<class 'numpy.float64'>


# np.zeros(rows,columns)
# np.ones(rows,columns)

In [203]:
# the ones and zeros array

zero_arr = np.zeros((10,10))
one_arr = np.ones((10,10))

print(f"{zero_arr}")
print(f"{one_arr}")

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


# np.linspace(start,stop,numberOfElements)

In [204]:
import math
print(f"{np.linspace(0,math.pi,10)}")
# 10 evenly spaced number between 0 and PI

[0.         0.34906585 0.6981317  1.04719755 1.3962634  1.74532925
 2.0943951  2.44346095 2.7925268  3.14159265]


# Identity Matrix

In [205]:
id_mat = np.eye(4)
print(f"{id_mat}")

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


# Random Arrays

In [206]:
np.random.rand(5)

array([0.65291954, 0.81307722, 0.58474304, 0.92856128, 0.70711184])

In [207]:
np.random.rand(5,5)

array([[0.37859459, 0.12135174, 0.88478985, 0.57815733, 0.99645591],
       [0.52142001, 0.97082682, 0.18706325, 0.07852021, 0.64025828],
       [0.92737879, 0.57298192, 0.71197114, 0.719739  , 0.52737939],
       [0.35591256, 0.81282077, 0.56283677, 0.42311043, 0.10395217],
       [0.54165123, 0.5760196 , 0.29558363, 0.90329984, 0.73688048]])

In [208]:
np.random.randn(2,2)

array([[-1.84821653, -0.73764049],
       [ 2.29783911, -0.59725311]])

In [209]:
np.random.randint(1,50)

24

In [210]:
np.random.randint(1,50,5)

array([ 1, 44, 40, 43, 37])

In [211]:
arr3 = np.arange(0,25,1)

In [212]:
arr3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [213]:
arr3.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

# Maximum , Minimum & Index Locations

In [214]:
rand_arr = np.random.randint(100,200,25)

In [215]:
rand_arr.reshape(5,5)

array([[166, 116, 198, 166, 165],
       [172, 198, 174, 191, 183],
       [168, 111, 104, 135, 110],
       [192, 128, 105, 109, 161],
       [120, 185, 102, 163, 158]])

In [216]:
print(f"Max Value : {rand_arr.max()} \nMin Value : {rand_arr.min()} \nRange : {rand_arr.max()-rand_arr.min()} \nIndex Position of Max Element : {rand_arr.argmax()} \nIndex Position of Min Element : {rand_arr.argmin()}")

Max Value : 198 
Min Value : 102 
Range : 96 
Index Position of Max Element : 2 
Index Position of Min Element : 22


In [217]:
rand_arr[19]

161

In [218]:
rand_arr[11]

111

In [219]:
arr4 = rand_arr.reshape(5,5)

In [220]:
arr4.shape

(5, 5)

In [221]:
arr4.dtype

dtype('int32')

In [222]:
type(arr4[0][1])

numpy.int32

In [223]:
from numpy import random
rand_arr1 = random.randint(0,100,20)
print(f"{rand_arr1}")

[ 0 48 38 65 48 65 91 83 54 86 89 69 94 86 76 25 30 88 67 47]


In [224]:
#alternative way

In [225]:
from numpy.random import randint
rand_arr2 = randint(0,100,20)
print(f"{rand_arr2}")

[40  3 51 36 26  4 70 75 54 40 46 31 76 16 21 50 54 52 83 39]


In [226]:
common_random_numbers_list = []
for i in rand_arr1:
    if i in rand_arr2:
        common_random_numbers_list.append(i)
print(f"Common Random  +ve Integers : {common_random_numbers_list}")

Common Random  +ve Integers : [83, 54, 76]


# Arrays Slicing . Indexing . Selection .

In [227]:
arr1 = np.arange(0,11)

In [228]:
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [229]:
arr1[::-1]

array([10,  9,  8,  7,  6,  5,  4,  3,  2,  1,  0])

In [230]:
arr1[1:5]

array([1, 2, 3, 4])

In [231]:
arr1[0]

0

In [232]:
type(arr1[0])

numpy.int32

# Broadcast

In [233]:
arr5 = np.arange(0,11)

In [234]:
arr5

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [235]:
slice_of_arr5 = arr5[:5] 

In [236]:
slice_of_arr5

array([0, 1, 2, 3, 4])

In [237]:
slice_of_arr5[:]

array([0, 1, 2, 3, 4])

In [238]:
slice_of_arr5[:] = 44

In [239]:
slice_of_arr5[:]

array([44, 44, 44, 44, 44])

In [240]:
slice_of_arr5

array([44, 44, 44, 44, 44])

In [241]:
# the original array has changed

In [242]:
arr5

array([44, 44, 44, 44, 44,  5,  6,  7,  8,  9, 10])

# Array Copy

In [243]:
arr_cpy = arr5.copy()

In [244]:
arr_cpy

array([44, 44, 44, 44, 44,  5,  6,  7,  8,  9, 10])

In [245]:
arr_cpy[:] = 33

In [246]:
arr_cpy

array([33, 33, 33, 33, 33, 33, 33, 33, 33, 33, 33])

In [247]:
# original array is still the same

In [248]:
arr5

array([44, 44, 44, 44, 44,  5,  6,  7,  8,  9, 10])

# Revisiting 2D Array

In [249]:
import numpy as np
arr_2d = np.array([[10,20,30],[40,50,60],[70,80,90]])

In [250]:
arr_2d

array([[10, 20, 30],
       [40, 50, 60],
       [70, 80, 90]])

In [251]:
arr_2d[0][0]

10

In [252]:
arr_2d[0]

array([10, 20, 30])

In [253]:
for i in range(0,len(arr_2d)):
    for j in range(0,len(arr_2d[i])):
        print(f"Row : {i+1} Column : {j+1} Element : {arr_2d[i][j]}")

Row : 1 Column : 1 Element : 10
Row : 1 Column : 2 Element : 20
Row : 1 Column : 3 Element : 30
Row : 2 Column : 1 Element : 40
Row : 2 Column : 2 Element : 50
Row : 2 Column : 3 Element : 60
Row : 3 Column : 1 Element : 70
Row : 3 Column : 2 Element : 80
Row : 3 Column : 3 Element : 90


# Sub-Matrix

In [254]:
arr_2d[:2,:2]

array([[10, 20],
       [40, 50]])

In [255]:
sub_arr2 = arr_2d[:2,:2]

In [256]:
sub_arr2

array([[10, 20],
       [40, 50]])

# Conditional Selection

In [257]:
import numpy as np
random_array = np.random.randint(0,100,9)

In [258]:
random_array

array([65, 47, 89, 49, 40, 86, 58, 34, 86])

In [259]:
bool_array = random_array > 35

In [260]:
bool_array

array([ True,  True,  True,  True,  True,  True,  True, False,  True])

In [261]:
random_array[bool_array]

array([65, 47, 89, 49, 40, 86, 58, 86])

In [262]:
random_array[random_array > 35]

array([65, 47, 89, 49, 40, 86, 58, 86])

In [263]:
arr1_2d = np.arange(0,100).reshape(10,10)

In [264]:
arr1_2d

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [265]:
array_60 = arr1_2d[arr1_2d>50]
array_60

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [266]:
array_70=array_60[array_60>60]
array_70

array([61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77,
       78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94,
       95, 96, 97, 98, 99])

In [267]:
array_80=array_70[array_70>70]
array_80

array([71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87,
       88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [268]:
array_90=array_80[array_80>80]
array_90

array([81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
       98, 99])

In [269]:
array_100=array_90[array_90>90]
array_100

array([91, 92, 93, 94, 95, 96, 97, 98, 99])

# NumPy Operations and Universal Functions ufunc

In [270]:
import numpy as np

In [271]:
arr6 = np.arange(0,100).reshape(10,10)

In [272]:
arr6

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [273]:
arr6*2

array([[  0,   2,   4,   6,   8,  10,  12,  14,  16,  18],
       [ 20,  22,  24,  26,  28,  30,  32,  34,  36,  38],
       [ 40,  42,  44,  46,  48,  50,  52,  54,  56,  58],
       [ 60,  62,  64,  66,  68,  70,  72,  74,  76,  78],
       [ 80,  82,  84,  86,  88,  90,  92,  94,  96,  98],
       [100, 102, 104, 106, 108, 110, 112, 114, 116, 118],
       [120, 122, 124, 126, 128, 130, 132, 134, 136, 138],
       [140, 142, 144, 146, 148, 150, 152, 154, 156, 158],
       [160, 162, 164, 166, 168, 170, 172, 174, 176, 178],
       [180, 182, 184, 186, 188, 190, 192, 194, 196, 198]])

In [274]:
arr6 // 2

array([[ 0,  0,  1,  1,  2,  2,  3,  3,  4,  4],
       [ 5,  5,  6,  6,  7,  7,  8,  8,  9,  9],
       [10, 10, 11, 11, 12, 12, 13, 13, 14, 14],
       [15, 15, 16, 16, 17, 17, 18, 18, 19, 19],
       [20, 20, 21, 21, 22, 22, 23, 23, 24, 24],
       [25, 25, 26, 26, 27, 27, 28, 28, 29, 29],
       [30, 30, 31, 31, 32, 32, 33, 33, 34, 34],
       [35, 35, 36, 36, 37, 37, 38, 38, 39, 39],
       [40, 40, 41, 41, 42, 42, 43, 43, 44, 44],
       [45, 45, 46, 46, 47, 47, 48, 48, 49, 49]], dtype=int32)

In [275]:
arr6 / 2

array([[ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5],
       [ 5. ,  5.5,  6. ,  6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5],
       [10. , 10.5, 11. , 11.5, 12. , 12.5, 13. , 13.5, 14. , 14.5],
       [15. , 15.5, 16. , 16.5, 17. , 17.5, 18. , 18.5, 19. , 19.5],
       [20. , 20.5, 21. , 21.5, 22. , 22.5, 23. , 23.5, 24. , 24.5],
       [25. , 25.5, 26. , 26.5, 27. , 27.5, 28. , 28.5, 29. , 29.5],
       [30. , 30.5, 31. , 31.5, 32. , 32.5, 33. , 33.5, 34. , 34.5],
       [35. , 35.5, 36. , 36.5, 37. , 37.5, 38. , 38.5, 39. , 39.5],
       [40. , 40.5, 41. , 41.5, 42. , 42.5, 43. , 43.5, 44. , 44.5],
       [45. , 45.5, 46. , 46.5, 47. , 47.5, 48. , 48.5, 49. , 49.5]])

In [276]:
arr7 = arr6.copy()

In [277]:
arr6 * arr7

array([[   0,    1,    4,    9,   16,   25,   36,   49,   64,   81],
       [ 100,  121,  144,  169,  196,  225,  256,  289,  324,  361],
       [ 400,  441,  484,  529,  576,  625,  676,  729,  784,  841],
       [ 900,  961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521],
       [1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401],
       [2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364, 3481],
       [3600, 3721, 3844, 3969, 4096, 4225, 4356, 4489, 4624, 4761],
       [4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929, 6084, 6241],
       [6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744, 7921],
       [8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801]])

In [278]:
arr6 + arr7

array([[  0,   2,   4,   6,   8,  10,  12,  14,  16,  18],
       [ 20,  22,  24,  26,  28,  30,  32,  34,  36,  38],
       [ 40,  42,  44,  46,  48,  50,  52,  54,  56,  58],
       [ 60,  62,  64,  66,  68,  70,  72,  74,  76,  78],
       [ 80,  82,  84,  86,  88,  90,  92,  94,  96,  98],
       [100, 102, 104, 106, 108, 110, 112, 114, 116, 118],
       [120, 122, 124, 126, 128, 130, 132, 134, 136, 138],
       [140, 142, 144, 146, 148, 150, 152, 154, 156, 158],
       [160, 162, 164, 166, 168, 170, 172, 174, 176, 178],
       [180, 182, 184, 186, 188, 190, 192, 194, 196, 198]])

In [279]:
arr6 ^ 2

array([[ 2,  3,  0,  1,  6,  7,  4,  5, 10, 11],
       [ 8,  9, 14, 15, 12, 13, 18, 19, 16, 17],
       [22, 23, 20, 21, 26, 27, 24, 25, 30, 31],
       [28, 29, 34, 35, 32, 33, 38, 39, 36, 37],
       [42, 43, 40, 41, 46, 47, 44, 45, 50, 51],
       [48, 49, 54, 55, 52, 53, 58, 59, 56, 57],
       [62, 63, 60, 61, 66, 67, 64, 65, 70, 71],
       [68, 69, 74, 75, 72, 73, 78, 79, 76, 77],
       [82, 83, 80, 81, 86, 87, 84, 85, 90, 91],
       [88, 89, 94, 95, 92, 93, 98, 99, 96, 97]], dtype=int32)

In [280]:
arr6 - arr7

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [281]:
arr7 ** 2

array([[   0,    1,    4,    9,   16,   25,   36,   49,   64,   81],
       [ 100,  121,  144,  169,  196,  225,  256,  289,  324,  361],
       [ 400,  441,  484,  529,  576,  625,  676,  729,  784,  841],
       [ 900,  961, 1024, 1089, 1156, 1225, 1296, 1369, 1444, 1521],
       [1600, 1681, 1764, 1849, 1936, 2025, 2116, 2209, 2304, 2401],
       [2500, 2601, 2704, 2809, 2916, 3025, 3136, 3249, 3364, 3481],
       [3600, 3721, 3844, 3969, 4096, 4225, 4356, 4489, 4624, 4761],
       [4900, 5041, 5184, 5329, 5476, 5625, 5776, 5929, 6084, 6241],
       [6400, 6561, 6724, 6889, 7056, 7225, 7396, 7569, 7744, 7921],
       [8100, 8281, 8464, 8649, 8836, 9025, 9216, 9409, 9604, 9801]],
      dtype=int32)

In [282]:
arr7 ** 2 + arr7[::-1] ** 2

array([[8100, 8282, 8468, 8658, 8852, 9050, 9252, 9458, 9668, 9882],
       [6500, 6682, 6868, 7058, 7252, 7450, 7652, 7858, 8068, 8282],
       [5300, 5482, 5668, 5858, 6052, 6250, 6452, 6658, 6868, 7082],
       [4500, 4682, 4868, 5058, 5252, 5450, 5652, 5858, 6068, 6282],
       [4100, 4282, 4468, 4658, 4852, 5050, 5252, 5458, 5668, 5882],
       [4100, 4282, 4468, 4658, 4852, 5050, 5252, 5458, 5668, 5882],
       [4500, 4682, 4868, 5058, 5252, 5450, 5652, 5858, 6068, 6282],
       [5300, 5482, 5668, 5858, 6052, 6250, 6452, 6658, 6868, 7082],
       [6500, 6682, 6868, 7058, 7252, 7450, 7652, 7858, 8068, 8282],
       [8100, 8282, 8468, 8658, 8852, 9050, 9252, 9458, 9668, 9882]],
      dtype=int32)

In [283]:
np.sqrt(arr6)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
        2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739,
        3.87298335, 4.        , 4.12310563, 4.24264069, 4.35889894],
       [4.47213595, 4.58257569, 4.69041576, 4.79583152, 4.89897949,
        5.        , 5.09901951, 5.19615242, 5.29150262, 5.38516481],
       [5.47722558, 5.56776436, 5.65685425, 5.74456265, 5.83095189,
        5.91607978, 6.        , 6.08276253, 6.164414  , 6.244998  ],
       [6.32455532, 6.40312424, 6.4807407 , 6.55743852, 6.63324958,
        6.70820393, 6.78232998, 6.8556546 , 6.92820323, 7.        ],
       [7.07106781, 7.14142843, 7.21110255, 7.28010989, 7.34846923,
        7.41619849, 7.48331477, 7.54983444, 7.61577311, 7.68114575],
       [7.74596669, 7.81024968, 7.87400787, 7.93725393, 8.        ,
        8.06225775, 8.1240384 , 8.18535277, 8.24621125, 8.30662386],
       [8.36660027, 8.42614977, 8.4852813

In [285]:
np.cumsum(arr6)

array([   0,    1,    3,    6,   10,   15,   21,   28,   36,   45,   55,
         66,   78,   91,  105,  120,  136,  153,  171,  190,  210,  231,
        253,  276,  300,  325,  351,  378,  406,  435,  465,  496,  528,
        561,  595,  630,  666,  703,  741,  780,  820,  861,  903,  946,
        990, 1035, 1081, 1128, 1176, 1225, 1275, 1326, 1378, 1431, 1485,
       1540, 1596, 1653, 1711, 1770, 1830, 1891, 1953, 2016, 2080, 2145,
       2211, 2278, 2346, 2415, 2485, 2556, 2628, 2701, 2775, 2850, 2926,
       3003, 3081, 3160, 3240, 3321, 3403, 3486, 3570, 3655, 3741, 3828,
       3916, 4005, 4095, 4186, 4278, 4371, 4465, 4560, 4656, 4753, 4851,
       4950], dtype=int32)

In [286]:
np.cumprod(arr6)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int32)

In [287]:
np.exp(arr6)

array([[1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
        5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
        2.98095799e+03, 8.10308393e+03],
       [2.20264658e+04, 5.98741417e+04, 1.62754791e+05, 4.42413392e+05,
        1.20260428e+06, 3.26901737e+06, 8.88611052e+06, 2.41549528e+07,
        6.56599691e+07, 1.78482301e+08],
       [4.85165195e+08, 1.31881573e+09, 3.58491285e+09, 9.74480345e+09,
        2.64891221e+10, 7.20048993e+10, 1.95729609e+11, 5.32048241e+11,
        1.44625706e+12, 3.93133430e+12],
       [1.06864746e+13, 2.90488497e+13, 7.89629602e+13, 2.14643580e+14,
        5.83461743e+14, 1.58601345e+15, 4.31123155e+15, 1.17191424e+16,
        3.18559318e+16, 8.65934004e+16],
       [2.35385267e+17, 6.39843494e+17, 1.73927494e+18, 4.72783947e+18,
        1.28516001e+19, 3.49342711e+19, 9.49611942e+19, 2.58131289e+20,
        7.01673591e+20, 1.90734657e+21],
       [5.18470553e+21, 1.40934908e+22, 3.83100800e+22, 1.04137594e+23,
   

In [288]:
np.max(arr6)

99

In [289]:
np.min(arr6)

0

In [290]:
np.sin(arr6)

array([[ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
        -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849],
       [-0.54402111, -0.99999021, -0.53657292,  0.42016704,  0.99060736,
         0.65028784, -0.28790332, -0.96139749, -0.75098725,  0.14987721],
       [ 0.91294525,  0.83665564, -0.00885131, -0.8462204 , -0.90557836,
        -0.13235175,  0.76255845,  0.95637593,  0.27090579, -0.66363388],
       [-0.98803162, -0.40403765,  0.55142668,  0.99991186,  0.52908269,
        -0.42818267, -0.99177885, -0.64353813,  0.29636858,  0.96379539],
       [ 0.74511316, -0.15862267, -0.91652155, -0.83177474,  0.01770193,
         0.85090352,  0.90178835,  0.12357312, -0.76825466, -0.95375265],
       [-0.26237485,  0.67022918,  0.98662759,  0.39592515, -0.55878905,
        -0.99975517, -0.521551  ,  0.43616476,  0.99287265,  0.63673801],
       [-0.30481062, -0.96611777, -0.7391807 ,  0.1673557 ,  0.92002604,
         0.82682868, -0.02655115, -0.85551998

In [291]:
np.cos(arr6)

array([[ 1.        ,  0.54030231, -0.41614684, -0.9899925 , -0.65364362,
         0.28366219,  0.96017029,  0.75390225, -0.14550003, -0.91113026],
       [-0.83907153,  0.0044257 ,  0.84385396,  0.90744678,  0.13673722,
        -0.75968791, -0.95765948, -0.27516334,  0.66031671,  0.98870462],
       [ 0.40808206, -0.54772926, -0.99996083, -0.53283302,  0.42417901,
         0.99120281,  0.64691932, -0.29213881, -0.96260587, -0.74805753],
       [ 0.15425145,  0.91474236,  0.83422336, -0.01327675, -0.84857027,
        -0.90369221, -0.12796369,  0.76541405,  0.95507364,  0.26664293],
       [-0.66693806, -0.98733928, -0.39998531,  0.5551133 ,  0.99984331,
         0.52532199, -0.43217794, -0.99233547, -0.64014434,  0.30059254],
       [ 0.96496603,  0.7421542 , -0.16299078, -0.91828279, -0.82930983,
         0.02212676,  0.85322011,  0.89986683,  0.11918014, -0.77108022],
       [-0.95241298, -0.25810164,  0.67350716,  0.98589658,  0.39185723,
        -0.56245385, -0.99964746, -0.5177698 

In [292]:
np.tan(arr6)

array([[ 0.00000000e+00,  1.55740772e+00, -2.18503986e+00,
        -1.42546543e-01,  1.15782128e+00, -3.38051501e+00,
        -2.91006191e-01,  8.71447983e-01, -6.79971146e+00,
        -4.52315659e-01],
       [ 6.48360827e-01, -2.25950846e+02, -6.35859929e-01,
         4.63021133e-01,  7.24460662e+00, -8.55993401e-01,
         3.00632242e-01,  3.49391565e+00, -1.13731371e+00,
         1.51589471e-01],
       [ 2.23716094e+00, -1.52749853e+00,  8.85165604e-03,
         1.58815308e+00, -2.13489670e+00, -1.33526407e-01,
         1.17875355e+00, -3.27370380e+00, -2.81429605e-01,
         8.87142844e-01],
       [-6.40533120e+00, -4.41695568e-01,  6.61006041e-01,
        -7.53130148e+01, -6.23498963e-01,  4.73814720e-01,
         7.75047091e+00, -8.40771255e-01,  3.10309661e-01,
         3.61455441e+00],
       [-1.11721493e+00,  1.60656699e-01,  2.29138799e+00,
        -1.49838734e+00,  1.77046993e-02,  1.61977519e+00,
        -2.08661353e+00, -1.24527568e-01,  1.20012724e+00,
        -3.

In [294]:
np.cosh(arr6)

array([[1.00000000e+00, 1.54308063e+00, 3.76219569e+00, 1.00676620e+01,
        2.73082328e+01, 7.42099485e+01, 2.01715636e+02, 5.48317035e+02,
        1.49047916e+03, 4.05154203e+03],
       [1.10132329e+04, 2.99370709e+04, 8.13773957e+04, 2.21206696e+05,
        6.01302142e+05, 1.63450869e+06, 4.44305526e+06, 1.20774764e+07,
        3.28299846e+07, 8.92411505e+07],
       [2.42582598e+08, 6.59407867e+08, 1.79245642e+09, 4.87240172e+09,
        1.32445611e+10, 3.60024497e+10, 9.78648047e+10, 2.66024120e+11,
        7.23128532e+11, 1.96566715e+12],
       [5.34323729e+12, 1.45244248e+13, 3.94814801e+13, 1.07321790e+14,
        2.91730871e+14, 7.93006726e+14, 2.15561577e+15, 5.85957119e+15,
        1.59279659e+16, 4.32967002e+16],
       [1.17692633e+17, 3.19921747e+17, 8.69637471e+17, 2.36391973e+18,
        6.42580006e+18, 1.74671355e+19, 4.74805971e+19, 1.29065644e+20,
        3.50836796e+20, 9.53673286e+20],
       [2.59235276e+21, 7.04674541e+21, 1.91550400e+22, 5.20687972e+22,
   

In [295]:
np.sinh(arr6)

array([[0.00000000e+00, 1.17520119e+00, 3.62686041e+00, 1.00178749e+01,
        2.72899172e+01, 7.42032106e+01, 2.01713157e+02, 5.48316123e+02,
        1.49047883e+03, 4.05154190e+03],
       [1.10132329e+04, 2.99370708e+04, 8.13773957e+04, 2.21206696e+05,
        6.01302142e+05, 1.63450869e+06, 4.44305526e+06, 1.20774764e+07,
        3.28299846e+07, 8.92411505e+07],
       [2.42582598e+08, 6.59407867e+08, 1.79245642e+09, 4.87240172e+09,
        1.32445611e+10, 3.60024497e+10, 9.78648047e+10, 2.66024120e+11,
        7.23128532e+11, 1.96566715e+12],
       [5.34323729e+12, 1.45244248e+13, 3.94814801e+13, 1.07321790e+14,
        2.91730871e+14, 7.93006726e+14, 2.15561577e+15, 5.85957119e+15,
        1.59279659e+16, 4.32967002e+16],
       [1.17692633e+17, 3.19921747e+17, 8.69637471e+17, 2.36391973e+18,
        6.42580006e+18, 1.74671355e+19, 4.74805971e+19, 1.29065644e+20,
        3.50836796e+20, 9.53673286e+20],
       [2.59235276e+21, 7.04674541e+21, 1.91550400e+22, 5.20687972e+22,
   

In [296]:
np.tanh(arr6)

array([[0.        , 0.76159416, 0.96402758, 0.99505475, 0.9993293 ,
        0.9999092 , 0.99998771, 0.99999834, 0.99999977, 0.99999997],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.        , 1.        , 1.        ,
        1.        , 1.        , 1.        , 1.        , 1.        ],
       [1.        , 1.        , 1.       

In [298]:
np.log(arr6)
# log 0 runtime warning

<ipython-input-298-987024e50039>:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr6)


array([[      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
        1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458],
       [2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
        2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898],
       [2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383,
        3.21887582, 3.25809654, 3.29583687, 3.33220451, 3.36729583],
       [3.40119738, 3.4339872 , 3.4657359 , 3.49650756, 3.52636052,
        3.55534806, 3.58351894, 3.61091791, 3.63758616, 3.66356165],
       [3.68887945, 3.71357207, 3.73766962, 3.76120012, 3.78418963,
        3.80666249, 3.8286414 , 3.8501476 , 3.87120101, 3.8918203 ],
       [3.91202301, 3.93182563, 3.95124372, 3.97029191, 3.98898405,
        4.00733319, 4.02535169, 4.04305127, 4.06044301, 4.07753744],
       [4.09434456, 4.11087386, 4.12713439, 4.14313473, 4.15888308,
        4.17438727, 4.18965474, 4.20469262, 4.21950771, 4.2341065 ],
       [4.24849524, 4.26267988, 4.2766661